default_language_version:
    python: python3.8

repos:
      - repo: https://github.com/pre-commit/pre-commit-hooks
        rev: v4.3.0
        hooks:
          - id: check-json
          - id: check-toml
          - id: check-yaml
            args: [--allow-multiple-documents]
          - id: end-of-file-fixer
          - id: mixed-line-ending
          - id: trailing-whitespace
            args: [--markdown-linebreak-ext=md]
            exclude: "setup.cfg"

      - repo: https://github.com/psf/black
        rev: 22.6.0
        hooks:
          - id: black

      - repo: https://github.com/PyCQA/flake8
        rev: 6.0.0
        hooks:
          - id: flake8
            args: [--max-line-length=150, --extend-ignore=E203]

      - repo: https://github.com/PyCQA/isort
        rev: 5.12.0
        hooks:
          - id: isort
            args: ["--profile", "black"]

      - repo: https://github.com/pre-commit/mirrors-mypy
        rev: v0.961
        hooks:
          - id: mypy
            files: ^dot/
            args: [--ignore-missing, --no-strict-optional]
            additional_dependencies: [types-pyyaml, types-requests]
