services:
  dot:
    build:
      context: .
      dockerfile: Dockerfile
    # Set environment variables, if needed
    environment:
      - PYTHONUNBUFFERED=1
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility
      - NVIDIA_VISIBLE_DEVICES=all
    # Preserve files across container restarts
    volumes:
      - .:/dot
    # Use NVIDIA runtime to enable GPU support in the container
    runtime: nvidia
    entrypoint: /bin/bash
    ports:
      - "8080:8080"
    container_name: dot
    stdin_open: true
    tty: true
