name: code-check

on:
    push:
        branches:
            - main
    pull_request:
        types: [opened, synchronize, reopened, ready_for_review]

jobs:
    code-check:
        if: github.event.pull_request.draft == false
        runs-on: ubuntu-latest
        steps:
            - name: Code Checkout
              uses: actions/checkout@v2

            - name: Set up Python 3.8
              uses: actions/setup-python@v2
              with:
                  python-version: 3.8
                  cache: 'pip'
                  cache-dependency-path: 'requirements*.txt'

            - uses: actions/cache@v3
              with:
                  path: ~/.cache/pre-commit
                  key: ${{ runner.os }}-pre-commit-${{ hashFiles('.pre-commit-config.yaml') }}

            - name: Code Check
              run: |
                  pip install pre-commit
                  pre-commit run --all --show-diff-on-failure
